// Copyright 2026 educrvz and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package mcp

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	mcplib "github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
	"github.com/educrvz/shopper-pp-cli/internal/cli"
	"github.com/educrvz/shopper-pp-cli/internal/client"
	"github.com/educrvz/shopper-pp-cli/internal/cliutil"
	"github.com/educrvz/shopper-pp-cli/internal/config"
	"github.com/educrvz/shopper-pp-cli/internal/mcp/cobratree"
	"github.com/educrvz/shopper-pp-cli/internal/store"
)

// RegisterTools registers all API operations as MCP tools.
func RegisterTools(s *server.MCPServer) {
	s.AddTool(
		mcplib.NewTool("address_list_address",
			mcplib.WithDescription("List the saved delivery addresses for the authenticated Shopper account. Takes no parameters; results are scoped to the bearer token. Returns the address book (each entry with its id, label, and location fields). Call this to discover which address a delivery or cart is bound to before scheduling or rescheduling."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/address/", true, false, nil, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("cart_add",
			mcplib.WithDescription("Add a product to the cart or increase its quantity. Required: id, quantity. Optional: engine. Returns the new cart."),
			mcplib.WithNumber("id", mcplib.Required(), mcplib.Description("Product ID to add")),
			mcplib.WithNumber("quantity", mcplib.Required(), mcplib.Description("Quantity to add (increments existing)")),
			mcplib.WithString("engine", mcplib.Description("Catalog engine (default SHOPPER)")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/cart/add", false, false, nil, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "body"}, {PublicName: "quantity", WireName: "quantity", Location: "body"}, {PublicName: "engine", WireName: "engine", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("cart_list_summary",
			mcplib.WithDescription("Fetch the current cart summary for the authenticated account: line items, quantities, and totals as the store computes them. Takes no parameters; the cart is keyed off the bearer token. Use this to read cart state after cart_add/cart_remove, or before checkout — it reflects the server-side cart, not a local copy. Returns the summary."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/cart/summary", true, false, nil, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("cart_remove",
			mcplib.WithDescription("Remove a product from the cart or decrease its quantity. Required: id, quantity. Returns the new cart."),
			mcplib.WithNumber("id", mcplib.Required(), mcplib.Description("Product ID to remove")),
			mcplib.WithNumber("quantity", mcplib.Required(), mcplib.Description("Quantity to remove (decrements; full qty removes the line)")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/cart/remove", false, false, nil, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "body"}, {PublicName: "quantity", WireName: "quantity", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("catalog_create_count",
			mcplib.WithDescription("POST /catalog/search/count. Required: brands, metadata, types. Optional: query. Returns the new count."),
			mcplib.WithString("query", mcplib.Description("")),
			mcplib.WithString("brands", mcplib.Required(), mcplib.Description("")),
			mcplib.WithString("metadata", mcplib.Required(), mcplib.Description("")),
			mcplib.WithString("types", mcplib.Required(), mcplib.Description("")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/catalog/search/count", false, false, nil, []mcpParamBinding{{PublicName: "query", WireName: "query", Location: "query"}, {PublicName: "brands", WireName: "brands", Location: "body"}, {PublicName: "metadata", WireName: "metadata", Location: "body"}, {PublicName: "types", WireName: "types", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("catalog_create_filters",
			mcplib.WithDescription("POST /catalog/search/filters. Required: brands, metadata, types. Optional: query. Returns the new filters."),
			mcplib.WithString("query", mcplib.Description("")),
			mcplib.WithString("brands", mcplib.Required(), mcplib.Description("")),
			mcplib.WithString("metadata", mcplib.Required(), mcplib.Description("")),
			mcplib.WithString("types", mcplib.Required(), mcplib.Description("")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/catalog/search/filters", false, false, nil, []mcpParamBinding{{PublicName: "query", WireName: "query", Location: "query"}, {PublicName: "brands", WireName: "brands", Location: "body"}, {PublicName: "metadata", WireName: "metadata", Location: "body"}, {PublicName: "types", WireName: "types", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("catalog_create_search",
			mcplib.WithDescription("POST /catalog/search. Required: brands, metadata, types. Optional: page, query, size. Returns the new search."),
			mcplib.WithNumber("page", mcplib.Description("")),
			mcplib.WithString("query", mcplib.Description("")),
			mcplib.WithNumber("size", mcplib.Description("")),
			mcplib.WithString("brands", mcplib.Required(), mcplib.Description("")),
			mcplib.WithString("metadata", mcplib.Required(), mcplib.Description("")),
			mcplib.WithString("types", mcplib.Required(), mcplib.Description("")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/catalog/search", false, false, nil, []mcpParamBinding{{PublicName: "page", WireName: "page", Location: "query"}, {PublicName: "query", WireName: "query", Location: "query"}, {PublicName: "size", WireName: "size", Location: "query"}, {PublicName: "brands", WireName: "brands", Location: "body"}, {PublicName: "metadata", WireName: "metadata", Location: "body"}, {PublicName: "types", WireName: "types", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("catalog_get_view",
			mcplib.WithDescription("GET /catalog/banners/{banner_id}/view. Required: banner_id. Returns the view."),
			mcplib.WithString("banner_id", mcplib.Required(), mcplib.Description("The banner_id path segment")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/catalog/banners/{banner_id}/view", true, false, nil, []mcpParamBinding{{PublicName: "banner_id", WireName: "banner_id", Location: "path"}}, []string{"banner_id"}),
	)
	s.AddTool(
		mcplib.NewTool("catalog_list_banners",
			mcplib.WithDescription("GET /catalog/banners. Optional: imageSize. Returns the banners."),
			mcplib.WithString("imageSize", mcplib.Description("")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/catalog/banners", true, false, nil, []mcpParamBinding{{PublicName: "imageSize", WireName: "imageSize", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("catalog_list_departments",
			mcplib.WithDescription("List the Shopper catalog's top-level departments (the store's category tree used for browsing). Takes no parameters. Returns each department with its id and name. Use this to map a free-text department name to the id needed when filtering catalog search."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/catalog/departments", true, false, nil, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("catalog_list_news",
			mcplib.WithDescription("List newly added products in the Shopper catalog (the store's 'what's new' feed). Takes no parameters. Returns recently introduced products with id, name, and price. Prefer this over catalog_search when you want recent arrivals rather than a keyword query."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/catalog/products/news", true, false, nil, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("catalog_list_suggest",
			mcplib.WithDescription("GET /catalog/search/suggest. Optional: query. Returns the suggest."),
			mcplib.WithString("query", mcplib.Description("")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/catalog/search/suggest", true, false, nil, []mcpParamBinding{{PublicName: "query", WireName: "query", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("delivery_list_calendar",
			mcplib.WithDescription("Fetch the delivery reschedule calendar from /delivery/v2/calendar: the date-picker configuration the store uses, i.e. the allowed reschedule date range and the set of disabled (unavailable) days. Takes no parameters; scoped to the account's active order. Use this to find which dates a delivery may be moved to before calling a reschedule; pair with delivery_list_summary to see the currently scheduled date. Returns the calendar."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/delivery/v2/calendar", true, false, nil, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("delivery_list_summary",
			mcplib.WithDescription("Fetch the current delivery summary from /delivery/summary: the scheduled delivery date and related order-timing fields (charge and cutoff/lock dates the store derives from it) for the authenticated account. Takes no parameters. Use this to see when the next basket is scheduled to arrive; pair with delivery_list_calendar for the dates it can be moved to. Returns the summary."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/delivery/summary", true, false, nil, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("features_create_select",
			mcplib.WithDescription("POST /features/stores/select. Required: store_id. Returns the new select."),
			mcplib.WithNumber("store_id", mcplib.Required(), mcplib.Description("")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/features/stores/select", false, false, nil, []mcpParamBinding{{PublicName: "store_id", WireName: "store_id", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("features_create_start",
			mcplib.WithDescription("POST /features/timer/start. Required: name. Returns the new start."),
			mcplib.WithString("name", mcplib.Required(), mcplib.Description("")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/features/timer/start", false, false, nil, []mcpParamBinding{{PublicName: "name", WireName: "name", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("features_create_view",
			mcplib.WithDescription("POST /features/toggle/view. Required: toggle. Returns the new view."),
			mcplib.WithString("toggle", mcplib.Required(), mcplib.Description("")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/features/toggle/view", false, false, nil, []mcpParamBinding{{PublicName: "toggle", WireName: "toggle", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("features_list_stores",
			mcplib.WithDescription("GET /features/stores. Optional: toggles. Returns the stores."),
			mcplib.WithString("toggles", mcplib.Description("")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/features/stores", true, false, nil, []mcpParamBinding{{PublicName: "toggles", WireName: "toggles", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("features_list_tick",
			mcplib.WithDescription("Read the current server timer tick from /features/timer/tick — the countdown/clock value the store uses to gate time-bound flows such as the order edit/cutoff window. Takes no parameters. Returns the current tick state. Use this to check how much time remains before the cart locks rather than computing it client-side."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/features/timer/tick", true, false, nil, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("features_list_toggle",
			mcplib.WithDescription("Read the active feature flags (toggles) for the authenticated session from /features/toggle. Takes no parameters. Returns the set of enabled feature flags. Use this to detect which store capabilities are available to this account before invoking a feature-gated command."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/features/toggle", true, false, nil, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("session_list_social",
			mcplib.WithDescription("Validate the current social-login session via /auth/validation/social. Takes no parameters; validates the bearer token's social-auth state. Returns the session/social validation result. Use this to confirm the configured token is still authenticated before running account-scoped commands."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/auth/validation/social", true, false, nil, []mcpParamBinding{}, []string{}),
	)
	// Search tool — faster than iterating list endpoints for finding specific items
	s.AddTool(
		mcplib.NewTool("search",
			mcplib.WithDescription("Full-text search across all synced data. Faster than paginating list endpoints. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("Search query (supports FTS5 syntax: AND, OR, NOT, quotes for phrases)")),
			mcplib.WithNumber("limit", mcplib.Description("Max results (default 25)")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleSearch,
	)
	// SQL tool — ad-hoc analysis on synced data without API calls
	s.AddTool(
		mcplib.NewTool("sql",
			mcplib.WithDescription("Run read-only SQL against local database. Use for ad-hoc analysis, aggregations, and joins across synced resources. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("SQL query (SELECT or WITH...SELECT). Tables match resource names.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleSQL,
	)

	// Context tool — front-loaded domain knowledge for agents.
	// Call this first to understand the API taxonomy, query patterns, and capabilities.
	s.AddTool(
		mcplib.NewTool("context",
			mcplib.WithDescription("Get API domain context: resource taxonomy, auth requirements, query tips, and unique capabilities. Call this first."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleContext,
	)

	// Runtime Cobra-tree mirror — exposes every user-facing command that is
	// not already covered by a typed endpoint or framework MCP tool.
	cobratree.RegisterAll(s, cli.RootCmd(), cobratree.SiblingCLIPath)
}

type mcpParamBinding struct {
	PublicName string
	WireName   string
	Location   string
}

// makeAPIHandler creates a generic MCP tool handler for an API endpoint.
func makeAPIHandler(method, pathTemplate string, readOnly bool, binaryResponse bool, headerOverrides map[string]string, bindings []mcpParamBinding, positionalParams []string) server.ToolHandlerFunc {
	return func(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
		c, err := newMCPClient()
		if err != nil {
			return mcplib.NewToolResultError(err.Error()), nil
		}

		// mcp-go v0.47+ made CallToolParams.Arguments an `any` to support
		// non-map payloads; GetArguments() returns the map[string]any shape
		// we rely on here (or an empty map when the payload is something else).
		args := req.GetArguments()

		// positionalParams mixes real URL path params with CLI positional
		// args that map to query params (e.g. `search <query>` -> ?query=);
		// the placeholder check below disambiguates them at runtime.
		path := pathTemplate
		knownArgs := make(map[string]bool, len(bindings))
		pathParams := make(map[string]bool, len(positionalParams))
		params := make(map[string]string)
		bodyArgs := make(map[string]any)
		var headers map[string]string
		if len(headerOverrides) > 0 {
			headers = make(map[string]string, len(headerOverrides)+1)
			for k, v := range headerOverrides {
				headers[k] = v
			}
		}
		if binaryResponse {
			if headers == nil {
				headers = map[string]string{}
			}
			headers[client.BinaryResponseHeader] = "true"
		}
		for _, binding := range bindings {
			knownArgs[binding.PublicName] = true
			v, ok := args[binding.PublicName]
			if !ok {
				continue
			}
			switch binding.Location {
			case "path":
				placeholder := "{" + binding.WireName + "}"
				pathParams[binding.PublicName] = true
				path = strings.Replace(path, placeholder, fmt.Sprintf("%v", v), 1)
			case "body":
				bodyArgs[binding.WireName] = v
			default:
				params[binding.WireName] = fmt.Sprintf("%v", v)
			}
		}
		for _, p := range positionalParams {
			placeholder := "{" + p + "}"
			if !strings.Contains(pathTemplate, placeholder) {
				continue
			}
			pathParams[p] = true
			if v, ok := args[p]; ok {
				path = strings.Replace(path, placeholder, fmt.Sprintf("%v", v), 1)
			}
		}

		for k, v := range args {
			if pathParams[k] || knownArgs[k] {
				continue
			}
			switch method {
			case "POST", "PUT", "PATCH":
				bodyArgs[k] = v
			default:
				params[k] = fmt.Sprintf("%v", v)
			}
		}

		var data json.RawMessage
		switch method {
		case "GET":
			if len(headers) > 0 {
				data, err = c.GetWithHeaders(ctx, path, params, headers)
				break
			}
			data, err = c.Get(ctx, path, params)
		case "POST":
			if len(headers) > 0 {
				if readOnly {
					data, _, err = c.PostQueryWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				} else {
					data, _, err = c.PostWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				}
				break
			}
			if readOnly {
				data, _, err = c.PostQueryWithParams(ctx, path, params, bodyArgs)
			} else {
				data, _, err = c.PostWithParams(ctx, path, params, bodyArgs)
			}
		case "PUT":
			if len(headers) > 0 {
				data, _, err = c.PutWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				break
			}
			data, _, err = c.PutWithParams(ctx, path, params, bodyArgs)
		case "PATCH":
			if len(headers) > 0 {
				data, _, err = c.PatchWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				break
			}
			data, _, err = c.PatchWithParams(ctx, path, params, bodyArgs)
		case "DELETE":
			if len(headers) > 0 {
				data, _, err = c.DeleteWithParamsAndHeaders(ctx, path, params, headers)
				break
			}
			data, _, err = c.DeleteWithParams(ctx, path, params)
		default:
			return mcplib.NewToolResultError("unsupported method: " + method), nil
		}

		if err != nil {
			msg := err.Error()
			switch {
			case strings.Contains(msg, "HTTP 409"):
				return mcplib.NewToolResultText("already exists (no-op)"), nil
			case strings.Contains(msg, "HTTP 400") && cliutil.LooksLikeAuthError(msg):
				return mcplib.NewToolResultError("authentication error: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: the API rejected the request — this usually means auth is missing or invalid." +
					"\n      Set your API key: export SHOPPER_TOKEN=<your-key>" +
					"\n      Run 'shopper-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 401"):
				return mcplib.NewToolResultError("authentication failed: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: check your token." +
					"\n      Set it with: export SHOPPER_TOKEN=<your-key>" +
					"\n      Run 'shopper-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 403"):
				return mcplib.NewToolResultError("permission denied: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: your credentials are valid but lack access to this resource." +
					"\n      Set it with: export SHOPPER_TOKEN=<your-key>" +
					"\n      Run 'shopper-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 404"):
				if method == "DELETE" {
					return mcplib.NewToolResultText("already deleted (no-op)"), nil
				}
				return mcplib.NewToolResultError("not found: " + msg), nil
			case strings.Contains(msg, "HTTP 429"):
				return mcplib.NewToolResultError("rate limited: " + msg), nil
			default:
				return mcplib.NewToolResultError(msg), nil
			}
		}

		// For GET responses, wrap bare arrays with count metadata
		if method == "GET" {
			trimmed := strings.TrimSpace(string(data))
			if len(trimmed) > 0 && trimmed[0] == '[' {
				var items []json.RawMessage
				if json.Unmarshal(data, &items) == nil {
					wrapped := map[string]any{
						"count": len(items),
						"items": items,
					}
					out, _ := json.Marshal(wrapped)
					return mcplib.NewToolResultText(string(out)), nil
				}
			}
		}
		if binaryResponse {
			out, _ := json.Marshal(map[string]any{
				"content_encoding": "base64",
				"data_base64":      base64.StdEncoding.EncodeToString(data),
				"byte_count":       len(data),
			})
			return mcplib.NewToolResultText(string(out)), nil
		}
		return mcplib.NewToolResultText(string(data)), nil
	}
}

func newMCPClient() (*client.Client, error) {
	home, _ := os.UserHomeDir()
	cfgPath := filepath.Join(home, ".config", "shopper-pp-cli", "config.toml")
	cfg, err := config.Load(cfgPath)
	if err != nil {
		return nil, fmt.Errorf("loading config: %w", err)
	}
	c := client.New(cfg, 60*time.Second, 2)
	// Agents calling through MCP need fresh data every call. The on-disk
	// response cache survives across MCP server invocations, so a
	// DELETE/PATCH followed by a GET would otherwise return the
	// pre-mutation snapshot for up to the cache TTL. The interactive CLI
	// constructs its own client and is unaffected.
	c.NoCache = true
	return c, nil
}

func dbPath() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".local", "share", "shopper-pp-cli", "data.db")
}

// Note: MCP tools use their own dbPath() because they are in a separate package (main, not cli).
// The CLI's defaultDBPath() in the cli package uses the same canonical path.

func handleSearch(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || query == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}

	limit := 25
	if v, ok := args["limit"].(float64); ok && v > 0 {
		limit = int(v)
	}

	db, err := store.OpenReadOnly(dbPath())
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("opening database: %v", err)), nil
	}
	defer db.Close()

	results, err := db.Search(query, limit)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("search failed: %v", err)), nil
	}

	data, _ := json.MarshalIndent(results, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

// validateReadOnlyQuery gates the MCP sql tool. The agent contract advertised
// to the host is ReadOnlyHintAnnotation(true); a false annotation on a
// mutating tool lets MCP hosts auto-approve writes and is treated as a real
// bug per the project's agent-native security model.
//
// The gate is an allowlist (SELECT or WITH only) applied AFTER stripping the
// leading whitespace, line comments, block comments, and semicolons that
// SQLite itself ignores before parsing. A naive HasPrefix check on a
// keyword blocklist is bypassable by prefixing the dangerous statement with
// "/* x */" or "-- x\n" — TrimSpace strips outer whitespace but does not
// understand SQL comment syntax. Combined with the empirical fact that
// modernc.org/sqlite's mode=ro does NOT block VACUUM INTO (writes a snapshot
// to a new file) or ATTACH DATABASE (opens a separate writable handle),
// such a bypass produces silent exfiltration to an attacker-chosen path.
//
// SELECT and WITH are the only allowed leading keywords. WITH supports
// SELECT-form CTEs; CTE-wrapped writes ("WITH x AS (...) INSERT ...") are
// caught by OpenReadOnly's mode=ro one layer down. PRAGMA, ATTACH, VACUUM,
// and every other DDL/DML keyword fail at this gate before reaching SQLite.
func validateReadOnlyQuery(query string) error {
	upper := strings.ToUpper(stripLeadingSQLNoise(query))
	if !strings.HasPrefix(upper, "SELECT") && !strings.HasPrefix(upper, "WITH") {
		return fmt.Errorf("only SELECT queries are allowed")
	}
	return nil
}

// stripLeadingSQLNoise removes leading whitespace, SQL line comments
// (-- to end of line), block comments (/* ... */), and statement
// separators (;) from query. SQLite skips these before parsing the first
// keyword, so a security gate that does not strip them mismatches what the
// driver actually executes.
func stripLeadingSQLNoise(query string) string {
	for {
		query = strings.TrimLeft(query, " \t\r\n;")
		switch {
		case strings.HasPrefix(query, "--"):
			if idx := strings.IndexByte(query, '\n'); idx >= 0 {
				query = query[idx+1:]
				continue
			}
			return ""
		case strings.HasPrefix(query, "/*"):
			if idx := strings.Index(query[2:], "*/"); idx >= 0 {
				query = query[2+idx+2:]
				continue
			}
			return ""
		default:
			return query
		}
	}
}

func handleSQL(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || query == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}

	if err := validateReadOnlyQuery(query); err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}

	db, err := store.OpenReadOnly(dbPath())
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("opening database: %v", err)), nil
	}
	defer db.Close()

	rows, err := db.Query(query)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("query failed: %v", err)), nil
	}
	defer rows.Close()

	cols, _ := rows.Columns()
	var results []map[string]any
	for rows.Next() {
		values := make([]any, len(cols))
		ptrs := make([]any, len(cols))
		for i := range values {
			ptrs[i] = &values[i]
		}
		rows.Scan(ptrs...)
		row := make(map[string]any)
		for i, col := range cols {
			row[col] = values[i]
		}
		results = append(results, row)
	}

	data, _ := json.MarshalIndent(results, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

func handleContext(_ context.Context, _ mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	ctx := map[string]any{
		"api":         "shopper",
		"description": "Shopper (shopper.com.br) — Brazilian online supermarket.",
		"archetype":   "generic",
		"tool_count":  21,
		// tool_surface tells agents which surface a capability lives on.
		"tool_surface": "MCP exposes typed endpoint tools plus a runtime mirror of user-facing CLI commands. Endpoint tools keep typed schemas; command-mirror tools shell out to the companion shopper-pp-cli binary.",
		"auth": map[string]any{
			"type": "bearer_token",
			"env_vars": []map[string]any{
				{
					"name":        "SHOPPER_TOKEN",
					"kind":        "per_call",
					"required":    true,
					"sensitive":   true,
					"description": "Set to your API credential.",
				},
			},
		},
		"resources": []map[string]any{
			{
				"name":        "address",
				"description": "Operations on address",
				"endpoints":   []string{"list_address"},
				"syncable":    true,
			},
			{
				"name":        "cart",
				"description": "Operations on summary",
				"endpoints":   []string{"add", "list_summary", "remove"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "catalog",
				"description": "Operations on departments",
				"endpoints":   []string{"create_count", "create_filters", "create_search", "get_view", "list_banners", "list_departments", "list_news", "list_suggest"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "delivery",
				"description": "Operations on summary",
				"endpoints":   []string{"list_calendar", "list_summary"},
				"syncable":    true,
			},
			{
				"name":        "features",
				"description": "Operations on toggle",
				"endpoints":   []string{"create_select", "create_start", "create_view", "list_stores", "list_tick", "list_toggle"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "session",
				"description": "Session and social-login validation",
				"endpoints":   []string{"list_social"},
				"syncable":    true,
			},
		},
		"query_tips": []string{
			"Pagination uses cursor-based paging. Pass page parameter for subsequent pages.",
			"Control page size with the limit parameter (default 100).",
			"Use the sql tool for ad-hoc analysis on synced data. Run sync first to populate the local database.",
			"Use the search tool for full-text search across all synced resources. Faster than iterating list endpoints.",
			"Prefer sql/search over repeated API calls when the data is already synced.",
		},
		// Command-mirror capabilities are exposed through MCP by shelling out
		// to the companion CLI binary.
		"command_mirror_capabilities": []map[string]string{
			{"name": "Charge & Edit Calendar", "command": "charge-calendar", "description": "Every upcoming cycle's charge date, edit-lock deadline", "rationale": "", "via": "mcp-command-mirror"},
			{"name": "Basket Diff", "command": "basket diff", "description": "Compares your current recurring basket against a previous cycle's snapshot to show exactly what was added, dropped", "rationale": "", "via": "mcp-command-mirror"},
			{"name": "Price Watch", "command": "price-watch", "description": "Tracks the price history of the SKUs you actually buy and alerts when one rises or drops meaningfully versus your own", "rationale": "", "via": "mcp-command-mirror"},
			{"name": "Restock Predictor", "command": "restock predict", "description": "Predicts when you'll run out of each staple from your historical buying cadence and suggests what to add to the", "rationale": "", "via": "mcp-command-mirror"},
			{"name": "Catalog Drift Detector", "command": "catalog drift", "description": "Flags products you buy that were discontinued, silently swapped, or kept their price while shrinking the pack", "rationale": "", "via": "mcp-command-mirror"},
			{"name": "Cashback Threshold Optimizer", "command": "cashback optimize", "description": "Computes the cheapest set of items to add (or whether to wait) to cross the next cashback tier", "rationale": "", "via": "mcp-command-mirror"},
		},
		"playbook": []map[string]string{
			{"topic": "Charge & Edit Calendar", "insight": ""},
			{"topic": "Basket Diff", "insight": ""},
			{"topic": "Price Watch", "insight": ""},
			{"topic": "Restock Predictor", "insight": ""},
			{"topic": "Catalog Drift Detector", "insight": ""},
			{"topic": "Cashback Threshold Optimizer", "insight": ""},
		},
	}
	data, _ := json.MarshalIndent(ctx, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

// RegisterNovelFeatureTools is kept as a compatibility no-op for older MCP
// mains. New generated mains call RegisterTools only; RegisterTools now
// includes the runtime Cobra-tree mirror.
func RegisterNovelFeatureTools(s *server.MCPServer) {
	_ = s
}
